### PR TITLE
Multi module

### PR DESCRIPTION
**Pull request by ampie**
Firstly, my apologies for losing the history of the Java files now in `operator-common`. I moved them out of the project first and then decided on a multi-module project instead. This PR contains:

1. Fix that ensures that we still include all the standard trusted issuers in the TrustStore
2. We don't need to read the CRD's anymore, as it required cluster scoped access
3. We have split the original operator project into two, which will allow us to start packaging different images
4. Some bugs were fixed in the end-to-end tests
5. The end-to-end tests now create the `entando-controllers` namespace, and ensures that all operations during the tests assume this namespace as the default namespace

### CODE REVIEW

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by ampie** [comment]
Retest this please

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by ampie** [comment]
Retest this please

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by ampie** [comment]
Retest this please

**Comment by entando-service** [comment]
All is well

**Comment by entando-service** [comment]
All is well

**Comment by ampie** [comment]
Retest this please

**Comment by entando-service** [comment]
All is well

**Pull request merged**
